pipeline {
    agent {
        docker {
            image 'python:3.9'
            args '-u root'
        }
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/bjesuslopezg/python-ci-test'
            }
        }

        stage('Setup Environment') {
            steps {
                script {
                    echo 'Setting up the environment...'
                    sh 'python -m venv venv'
                    sh '. venv/bin/activate && pip install -r requirements.txt'
                }
            }
        }

        stage('Run Tests') {
            steps {
                script {
                    echo 'Running tests...'
                    sh '. venv/bin/activate && pytest tests'
                }
            }
        }

        stage('Static Code Analysis') {
            steps {
                script {
                    echo 'Performing static code analysis...'
                    sh '. venv/bin/activate && pylint your_project_module'
                }
            }
            post {
                always {
                    script {
                        echo 'Static analysis completed.'
                    }
                }
                unsuccessful {
                    script {
                        echo 'Static analysis found issues.'
                        // Set the build result to unstable if static analysis is just nice to have
                        currentBuild.result = 'UNSTABLE'
                    }
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
